### ISSUE TITLE
"../firebase_common" is a relative path, but this isn't a local pubspec

### ISSUE THREAD

**Issue by SwissCheese5** [fluttercommunity/firebase_dart_sdk#16]
```
Resolving dependencies...
Error on line 11, column 11: Invalid description in the "firebase_firestore" pubspec on the "firebase_common" dependency: "../firebase_common" is a relative path, but this isn't a local pubspec.
   â•·
11 â”‚     path: ../firebase_common
   â”‚           ^^^^^^^^^^^^^^^^^^
   â•µ
Process finished with exit code 65
```
I tried following the example for firestore.

```yaml
dependencies:
  args: ^1.5.0
  shelf: ^0.7.5
  shelf_router: ^0.7.2
  shelf_body_parser: ^1.0.6
  json_annotation: ^3.0.0
  meta: ^1.1.8
  html_unescape: ^1.0.1+3
  firebase_common:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_common
  firebase_firestore:
    git:
      url: https://github.com/fluttercommunity/firebase_dart_sdk
      path: firebase_firestore
```
